# Generated by Django 4.0.6 on 2022-08-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernumber',
            name='expiry',
            field=models.DateField(null=True),
        ),
    ]
