# Generated by Django 4.0.6 on 2022-08-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0002_alter_membernumber_expiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("time", models.TimeField(auto_now_add=True)),
                ("member", models.ManyToManyField(to="gym_app.membernumber")),
            ],
            options={
                "verbose_name_plural": "Visits",
            },
        ),
    ]
