# Generated by Django 4.0.6 on 2022-08-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_rename_member_visits_member_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('maximum_people', models.IntegerField()),
                ('description', models.TextField()),
                ('event_host', models.ManyToManyField(to='gym_app.eventhosts')),
                ('members', models.ManyToManyField(to='gym_app.membernumber')),
            ],
        ),
    ]
