# Generated by Django 4.0.6 on 2022-08-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0006_eventhosts_events"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="description",
            new_name="event_description",
        ),
        migrations.RenameField(
            model_name="events",
            old_name="members",
            new_name="event_members",
        ),
        migrations.AddField(
            model_name="events",
            name="event_name",
            field=models.CharField(default="Test event", max_length=20),
            preserve_default=False,
        ),
    ]
